name: yuyan_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.1.1+1.1.1

environment:
  sdk: ">=2.7.0 <3.0.0"

# dependency_overrides:
#   chewie:
#     git:
#       url: https://github.com/masewo/chewie.git
dependency_overrides:
  flutter_webview_plugin:
    git: https://github.com/aboutmydreams/flutter_webview_plugin.git
  notus:
    git: https://github.com/aboutmydreams/notus.git
  # markdown / 富文本 编辑器
  zefyr:
    git: https://github.com/aboutmydreams/zefyr.git


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.7.0

  # goodlook bar
  curved_navigation_bar: ^0.3.1

  # goodlook guide 液体
  liquid_swipe: ^1.5.0
  flutter_swiper: 1.1.6

  # 解析html
  flutter_html: ^1.2.0

  # sha1 加密
  crypto: ^2.1.3

  # 网络请求
  dio: 3.0.10
  pretty_json: 1.1.0

  # 弱提示
  # fluttertoast: ^3.1.3
  bot_toast: 3.0.5

  # 下拉刷新
  pull_to_refresh: 1.6.3

  # 图片缓存
  cached_network_image: ^2.0.0

  # 图片查看
  extended_image: 1.1.1

  # 写入文件
  path_provider: ^1.6.11

  # 状态管理
  provider: ^4.0.4
  scoped_model: ^1.0.1
  get: 3.25.6

  # 数据分析
  firebase_core: ^0.5.3 # This dependency was added during initial configuration.
  firebase_analytics: ^6.3.0 # add dependency for Google Analytics for Firebase

  chewie: ^0.12.0

  # html
  flutter_widget_from_html: ^0.5.2+1

  # 缓存
  shared_preferences: ^0.5.8
  json_store: 1.2.0
  get_storage:

  # 分享
  share: ^0.6.4+3
  share_extend: ^1.1.9

  # 权限
  permission_handler: ^5.0.0+hotfix.8

  # webView
  webview_flutter: 1.0.7
  flutter_inappwebview: 4.0.0+4
  # git: https://github.com/aboutmydreams/flutter_inappwebview.git
  # flutter_webview_plugin: ^0.3.11

  # flare
  flare_flutter: ^2.0.6

  # request with cookie
  requests: ^3.0.3

  # use svg
  flutter_svg: ^0.19.1

  # 裁剪 我的页面顶部背景
  flutter_custom_clippers: ^1.1.0

  # 列表动画
  flutter_staggered_animations: ^0.1.2

  # 话题标签颜色
  smart_color: ^0.2.2

  # 消息红点
  badges: ^1.1.0

  # 图片放大
  photo_view: ^0.9.2

  # 评论 下滑出的抽屉
  sliding_up_panel: ^1.0.1

  # 更新apk https://github.com/xuexiangjys/XUpdate
  flutter_xupdate: ^1.0.2

  # 获取版本号
  package_info: ^0.4.3+2

  # 滑动tab
  shifting_tabbar: ^0.3.1

  # 图片选择器
  image_picker: ^0.6.7+22
  # multi_image_picker: ^4.7.14

  # lake to markdown
  html2md: ^0.5.1

  # markdown to quill
  # quill_markdown: ^0.0.3

  # markdown 渲染器
  flutter_markdown: ^0.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/js/doc_height.js
    - assets/flares/Like.flr
    - assets/flares/mark.flr
    - assets/flares/bird.flr
    - assets/flares/progress.flr
    - assets/images/logo.png
    - assets/images/paddy.svg
    - assets/images/first.jpg
    - assets/images/guide/guide1.png
    - assets/images/guide/guide2.png
    - assets/images/guide/guide3.png
    - assets/images/explore/book.png
    - assets/images/explore/fellower.png
    - assets/images/dashboard/link.png
    - assets/images/dashboard/link2.png
    - assets/images/dashboard/design.png
    - assets/images/dashboard/book.png
    - assets/images/dashboard/excel.png
    - assets/images/dashboard/doc.png
    - assets/images/news/read_all.png
    - assets/images/my_page/position.png
    - assets/images/my_page/location.png
    - assets/images/my_page/member.png
    - assets/images/my_page/exit.png
    - assets/images/my_page/follow_book.png
    - assets/images/my_page/suggest.png
    - assets/images/my_page/about.png
    - assets/images/my_page/setting.png
    - assets/images/my_page/collections.png
    - assets/images/my_page/topics.png
    - assets/images/my_page/history.png

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Silom
      fonts:
        - asset: assets/fonts/Silom.ttf
    - family: sans_bold
      fonts:
        - asset: assets/fonts/sans_bold.ttf
        # - asset: fonts/Schyler-Italic.ttf
        #   style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
